/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTS;

import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;

/**
 *
 * @author ASUS
 */
public class UTS extends javax.swing.JFrame {

    /**
     * Creates new form Syy
     */
    public UTS() {
        initComponents();
         this.setTitle("KASIR PEMBELIAN ALAT TULIS");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jButton1 = new javax.swing.JButton();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PILIH = new javax.swing.JComboBox<>();
        HARGA = new javax.swing.JTextField();
        TOTAL_BARANG = new javax.swing.JTextField();
        TOTAL = new javax.swing.JTextField();
        JML_BAYAR = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        hitung_jumlah_bayar = new javax.swing.JButton();
        bayar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        pembayaran_menu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jButton1.setText("jButton1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("KASIR SEDERHANA MEMBELI ALAT TULIS");

        jLabel2.setText("NAMA BARANG");

        jLabel3.setText("HARGA BARANG");

        jLabel4.setText("JUMLAH BELI");

        jLabel5.setText("TOTAL HARGA ");

        jLabel6.setText("JUMLAH BAYAR");

        jLabel7.setText("KEMBALIAN");

        PILIH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PILIH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH BARANG", "BUKU", "BOLPOIN", "PENSIL", "PENGGARIS", "PENGHAPUS" }));
        PILIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILIHActionPerformed(evt);
            }
        });

        HARGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HARGAActionPerformed(evt);
            }
        });

        TOTAL_BARANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTAL_BARANGActionPerformed(evt);
            }
        });

        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        hitung_jumlah_bayar.setText("HITUNG JUMLAH BAYAR");
        hitung_jumlah_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_jumlah_bayarActionPerformed(evt);
            }
        });

        bayar.setText("BAYAR");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        pembayaran_menu.setText("PEMBAYARAN PEMBELIAN ALAT TULIS");

        jMenuItem3.setText("KELUAR");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        pembayaran_menu.add(jMenuItem3);

        jMenuBar1.add(pembayaran_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hitung_jumlah_bayar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(79, 79, 79))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PILIH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HARGA)
                            .addComponent(TOTAL_BARANG)
                            .addComponent(TOTAL))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(keluar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(32, 32, 32)
                                        .addComponent(JML_BAYAR, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(batal)
                                .addGap(94, 94, 94)
                                .addComponent(bayar)
                                .addGap(31, 31, 31))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PILIH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(JML_BAYAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(HARGA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TOTAL_BARANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitung_jumlah_bayar)
                    .addComponent(bayar)
                    .addComponent(batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(keluar)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

     
        // Tambahkan handler untuk HARGA
private void HARGAActionPerformed(java.awt.event.ActionEvent evt) {
    // Tidak ada tindakan spesifik di sini (bisa disesuaikan sesuai kebutuhan)
}

// Tambahkan handler untuk TOTAL_BARANG
private void TOTAL_BARANGActionPerformed(java.awt.event.ActionEvent evt) {
    // Tidak ada tindakan spesifik di sini (bisa disesuaikan sesuai kebutuhan)
}

// Tambahkan handler untuk kembalian
private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {
    // Tidak ada tindakan spesifik di sini (bisa disesuaikan sesuai kebutuhan)
}
    
    private void hitung_jumlah_bayarActionPerformed(java.awt.event.ActionEvent evt) {
        int JumlahBarang = Integer.parseInt(TOTAL_BARANG.getText());
        int HargaBarang = Integer.parseInt(HARGA.getText());
        TOTAL.setText(Integer.toString(HargaBarang * JumlahBarang));
    }
    
    private void PILIHActionPerformed(java.awt.event.ActionEvent evt) {
    String NamaBarang = (String) PILIH.getSelectedItem();
    
    // Membuat objek dari BarangFactory
    BarangFactory factory = new BarangFactory();
    
    // Memanggil metode getBarang melalui objek factory
    Barang barang = factory.getBarang(NamaBarang); 
    
    // Set harga barang yang sesuai
    HARGA.setText(Integer.toString(barang.getHarga()));
}

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {
        HARGA.setText("");
        TOTAL_BARANG.setText("");
        TOTAL.setText("");
        JML_BAYAR.setText("");
        kembalian.setText("");
        PILIH.setSelectedIndex(0);
    }

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int hargaTotal = Integer.parseInt(TOTAL.getText());
            int UangBayar = Integer.parseInt(JML_BAYAR.getText());
            if (UangBayar < hargaTotal) {
                JOptionPane.showMessageDialog(null, "Uang Anda Kurang :V", "SYSTEM NOTICE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                kembalian.setText(Integer.toString(UangBayar - hargaTotal));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input angka yang valid", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Kelas Barang dan Factory harus non-statis
    class Barang {
        protected String nama;
        protected int harga;

        public Barang(String nama, int harga) {
            this.nama = nama;
            this.harga = harga;
        }

        public int getHarga() {
            return harga;
        }
    }

    class Buku extends Barang {
        public Buku() {
            super("Buku", 3000);
        }
    }

    class Bolpoin extends Barang {
        public Bolpoin() {
            super("Bolpoin", 2500);
        }
    }
    
    class Pensil extends Barang {
        public Pensil() {
            super("Pensil", 2000);
        }
    }

    class Penggaris extends Barang {
        public Penggaris() {
            super("Penggaris", 5000);
        }
    }
    
    class Penghapus extends Barang {
        public Penghapus() {
            super("Penghapus", 1000);
        }
    }

    class BarangFactory {
        Barang getBarang(String namaBarang) {
            switch (namaBarang) {
                case "BUKU":
                    return new Buku();
                case "BOLPOIN":
                    return new Bolpoin();
                case "PENSIL":
                    return new Pensil();
                case "PENGGARIS":
                    return new Penggaris();
                case "PENGHAPUS":
                    return new Penghapus();
                default:
                    return new Barang("Unknown", 0);
            }
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new UTS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HARGA;
    private javax.swing.JTextField JML_BAYAR;
    private javax.swing.JComboBox<String> PILIH;
    private javax.swing.JTextField TOTAL;
    private javax.swing.JTextField TOTAL_BARANG;
    private javax.swing.JButton batal;
    private javax.swing.JButton bayar;
    private javax.swing.JButton hitung_jumlah_bayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kembalian;
    private javax.swing.JMenu pembayaran_menu;
    // End of variables declaration//GEN-END:variables
}
