/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Asat_P9;

/**
 *
 * @author ASUS
 */
import javax.swing.JOptionPane;

public class Tugas9 extends javax.swing.JFrame {

    /**
     * Creates new form tugas9
     */
    public Tugas9() {
        initComponents();
        this.setTitle("MESIN KASIR SEDERHANA");
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PILIH = new javax.swing.JComboBox<>();
        HARGA = new javax.swing.JTextField();
        TOTAL_BARANG = new javax.swing.JTextField();
        TOTAL = new javax.swing.JTextField();
        JML_BAYAR = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        hitung_jumlah_bayar = new javax.swing.JButton();
        bayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("KASIR SEDERHANA MEMBELI ALAT TULIS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 300, 20);

        jLabel2.setText("NAMA BARANG");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 94, 85, 16);

        jLabel3.setText("HARGA BARANG");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 135, 90, 16);

        jLabel4.setText("JUMLAH BELI");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 175, 69, 16);

        jLabel5.setText("TOTAL HARGA ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 215, 81, 16);

        jLabel6.setText("JUMLAH BAYAR");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(342, 94, 85, 16);

        jLabel7.setText("KEMBALIAN");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(342, 175, 85, 16);

        PILIH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PILIH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH BARANG", "BUKU", "BOLPOIN", "PENSIL", "PENGGARIS", "PENGHAPUS", "TAS" }));
        PILIH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PILIHActionPerformed(evt);
            }
        });
        getContentPane().add(PILIH);
        PILIH.setBounds(175, 93, 122, 21);

        HARGA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HARGAActionPerformed(evt);
            }
        });
        getContentPane().add(HARGA);
        HARGA.setBounds(175, 132, 122, 22);

        TOTAL_BARANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTAL_BARANGActionPerformed(evt);
            }
        });
        getContentPane().add(TOTAL_BARANG);
        TOTAL_BARANG.setBounds(175, 172, 122, 22);
        getContentPane().add(TOTAL);
        TOTAL.setBounds(175, 212, 122, 22);
        getContentPane().add(JML_BAYAR);
        JML_BAYAR.setBounds(472, 91, 122, 22);

        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        getContentPane().add(kembalian);
        kembalian.setBounds(472, 172, 122, 22);

        batal.setText("BATAL");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal);
        batal.setBounds(24, 336, 72, 23);

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(522, 336, 72, 23);

        hitung_jumlah_bayar.setText("HITUNG JUMLAH BAYAR");
        hitung_jumlah_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung_jumlah_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(hitung_jumlah_bayar);
        hitung_jumlah_bayar.setBounds(230, 280, 162, 23);

        bayar.setText("BAYAR");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar);
        bayar.setBounds(273, 336, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HARGAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HARGAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HARGAActionPerformed

    private void TOTAL_BARANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTAL_BARANGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTAL_BARANGActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void hitung_jumlah_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung_jumlah_bayarActionPerformed
        // TODO add your handling code here:
        int JumlahBarang = Integer.parseInt(TOTAL_BARANG.getText());
        int HargaBarang = Integer.parseInt(HARGA.getText());
        TOTAL.setText(Integer.toString(HargaBarang * JumlahBarang));
    }//GEN-LAST:event_hitung_jumlah_bayarActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        HARGA.setText("");
        TOTAL_BARANG.setText("");
        TOTAL.setText("");
        JML_BAYAR.setText("");
        kembalian.setText("");
        PILIH.setSelectedIndex(0);
    }//GEN-LAST:event_batalActionPerformed

    private void PILIHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PILIHActionPerformed
        // TODO add your handling code here:
        String NamaBarang = (String) PILIH.getSelectedItem();
        switch (NamaBarang) {
            case "BUKU":
                HARGA.setText("3000");
                break;
            case "BOLPOIN":
                HARGA.setText("2500");
                break;
            case "PENSIL":
                HARGA.setText("2000");
                break;
            case "PENGGARIS":
                HARGA.setText("5000");
                break;
            case "PENGHAPUS":
                HARGA.setText("1000");
                break;
            case "TAS":
                HARGA.setText("50000");
                break;
    }//GEN-LAST:event_PILIHActionPerformed
    }

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO
        int hargaTotal = Integer.parseInt(TOTAL.getText());
        int UangBayar = Integer.parseInt(JML_BAYAR.getText());
        if ((UangBayar - hargaTotal) < 0) {
            JOptionPane.showMessageDialog(null, "Uang Anda Kurang :V", "SYSTEM NOTICE", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        kembalian.setText(Integer.toString(UangBayar - hargaTotal));
    }//GEN-LAST:event_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas9().setVisible(true);
                //new Tugas9().();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HARGA;
    private javax.swing.JTextField JML_BAYAR;
    private javax.swing.JComboBox<String> PILIH;
    private javax.swing.JTextField TOTAL;
    private javax.swing.JTextField TOTAL_BARANG;
    private javax.swing.JButton batal;
    private javax.swing.JButton bayar;
    private javax.swing.JButton hitung_jumlah_bayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kembalian;
    // End of variables declaration//GEN-END:variables
}
